buildscript {
    repositories {
        ivy {
            url project.getProperty("intermine.plugin.repo")
            layout "pattern", {
                artifact  "[artifact]-[revision].[ext]"
            }
            metadataSources {
                artifact()
            }
        }
        maven {
            url project.getProperty("intermine.maven.central")
        }
        maven {
            url project.getProperty("intermine.maven.plugins")
        }
    }
    dependencies {
        classpath group: 'org.intermine', name: 'plugin', version: System.getProperty("imVersion")
        classpath 'com.bmuschko:gradle-cargo-plugin:2.9.0'
    }
}

ext {
  mineName = "cadremine"
  buildEnvironment = project.getProperty("intermine.development.buildEnvironment")
  warEnvironment = project.getProperty("intermine.development.warEnvironment")

  mineBuildPropertyFileName = "${mineName}-${buildEnvironment}.properties"
  mineBuildPropertyFile = file("data/$mineBuildPropertyFileName")
  println "Using build properties file: '$mineBuildPropertyFile'"

  mineWarPropertyFileName = "${mineName}-${warEnvironment}.properties"
  mineWarPropertyFile = file("data/$mineWarPropertyFileName")
  println "Using WAR properties file: '$mineWarPropertyFile'"
}

subprojects {
  apply plugin: 'java'
  apply plugin: 'maven'

  sourceCompatibility = 1.8
  targetCompatibility = 1.8

  // -------------------------
  // Build localDirs list
  // -------------------------

  def intermineLocalDirs = []
  def intermineRootDir = project.getProperty("intermine.development.intermineRootDir")
  def intermineModules = project.getProperty("intermine.development.intermineModules")

  if (intermineRootDir && intermineModules) {
    println "Using intermineRootDir: $intermineRootDir"

    def modules = intermineModules.split(',').collect { it.trim() }.findAll { it }
    intermineLocalDirs = modules.collect {
        module -> "${intermineRootDir}/${module}/build/libs"
    }

    println "Using intermineLocalDirs: $intermineLocalDirs"
  }

  def bioLocalDirs = []
  def bioRootDir = project.getProperty("intermine.development.bioRootDir")
  def bioModules = project.getProperty("intermine.development.bioModules")

  if (bioRootDir && bioModules) {
    def modules = bioModules.split(',').collect { it.trim() }.findAll { it }
    bioLocalDirs = modules.collect {
        module -> "${bioRootDir}/${module}/build/libs"
    }
  }

  def localDirs = intermineLocalDirs + bioLocalDirs
  println "Using localDirs: $localDirs"

  repositories {
    // Prefer locally-built InterMine artifacts
    localDirs.each { dir ->
        ivy {
            url "file://" + dir
            layout "pattern", {
                artifact  "[artifact]-[revision](-[classifier]).[ext]"
            }
            metadataSources {
                artifact()
            }
        }
    }
    maven {
        url project.getProperty("intermine.maven.central")
    }
    maven {
        url project.getProperty("intermine.maven.clojars")
    }
  }

  dependencies {
    compile group: "org.intermine", name: "intermine-resources", version: System.getProperty("imVersion")
    compile('ant:ant:1.6.5')
    compile group: 'net.iharder', name: 'base64', version: '2.3.8'

    testCompile group: 'junit', name: 'junit', version: '4.8.2'
  }

  task copyMineProperties(type: Copy) {
    description "Copies mine specific intermine.properties file into resources output to be used for building the database"
    dependsOn 'processResources'
    from (mineBuildPropertyFile)
    into sourceSets.main.output.resourcesDir
    rename { fileName -> fileName.replace("$mineBuildPropertyFileName", "intermine.properties") }
    inputs.sourceFiles.stopExecutionIfEmpty()
  }
}

task clean(type: Delete) {
    println "cleaning"
    delete "idresolver.cache"
    println "deleting idresolver cache"
    delete "datasources.xml"
    println "deleting datasources.xml"
    delete "organisms.xml"
    println "deleting organisms.xml"
    delete "publications.xml"
    println "deleting publications.xml"
    delete fileTree('.') {
        include '*.log'
    }
    println "deleted log files"
}
