volumes:
  postgres_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "./data/postgres"

  solr_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "./data/solr"

  bluegenes_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "./data/bluegenes_tools"

  nexus_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "./data/nexus"

  tomcat_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "./data/tomcat"

services:
  postgres:
    container_name: intermine_postgres
    build:
      context: ./postgres
      dockerfile: ./postgres.Dockerfile
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_PORT}

  solr:
    container_name: intermine_solr
    build:
      context: ./solr
      dockerfile: ./solr.Dockerfile
    volumes:
      - solr_volume:/var/solr
    environment:
      - MEM_OPTS=${SOLR_MEM_OPTS}
      - MINE_NAME=${MINE_NAME}
    ports:
      - ${SOLR_HOST_PORT}:${SOLR_PORT}

  tomcat:
    container_name: intermine_tomcat
    build:
      context: ./tomcat
      dockerfile: ./tomcat.Dockerfile
    volumes:
      - tomcat_volume:/usr/local/tomcat/webapps
    environment:
      - MEM_OPTS=${TOMCAT_MEM_OPTS}
    ports:
      - ${TOMCAT_HOST_PORT}:${TOMCAT_PORT}

  bluegenes:
    container_name: intermine_bluegenes
    image: intermine/bluegenes:1.4.6-rc3
    volumes:
      - bluegenes_volume:/tools
    environment:
      - BLUEGENES_DEFAULT_SERVICE_ROOT="http://${TOMCAT_HOST}:${TOMCAT_HOST_PORT}/${MINE_NAME}"
      - BLUEGENES_BACKEND_SERVICE_ROOT="http://tomcat:${TOMCAT_PORT}/${MINE_NAME}"
      - BLUEGENES_DEFAULT_MINE_NAME=${MINE_NAME}
      - BLUEGENES_DEFAULT_NAMESPACE=${MINE_NAME}
    ports:
      - ${BLUEGENES_HOST_PORT}:${BLUEGENES_PORT}

  nexus:
    container_name: intermine_nexus
    image: sonatype/nexus3:3.89.1
    volumes:
      - nexus_volume:/nexus-data
    ports:
      - ${NEXUS_HOST_PORT}:${NEXUS_PORT}
