[common]
venv_dir = /intermine/venv
intermine_dir = /intermine/intermine

# Directory containing local Docker images e.g. dev Bluegenes
docker_images_dir = /intermine/release/docker_images

# OMOP CDM Schema CSV file
omop_schema_file = /intermine/omop/OMOP_CDMv5.4_Field_Level.csv

# Top level directory containing csv files
omop_data_dir = /intermine/data

# Location of the Intermine Tomcat server as seen from the Bluegenes frontend
bluegenes_default_service_domain = http://localhost:9999

# Account name for the superuser for all Intermines
superuser_account = admin@cadre

# Initial password for the superuser for all Intermines
superuser_initial_password = secret

# Set to False for development environment, True in SDE
offline = True

# Set if offline = True
gradle_dir = /intermine/release/gradle

# Probably no need to change this
nexus_host_port = 8081

projects =
   project1
   project2
