// Source - https://stackoverflow.com/a/27058232
// Posted by Rene Groeschke, modified by community. See post 'Timeline' for change history
// Retrieved 2026-02-12, License - CC BY-SA 3.0

allprojects{
    repositories {
        all { ArtifactRepository repo ->
            if ((repo instanceof MavenArtifactRepository) && (
                repo.url.toString().startsWith("https://repo1.maven.org") ||
                repo.url.toString().startsWith("https://repo.maven.apache.org") ||
                repo.url.toString().startsWith("https://www.ebi.ac.uk")
            ) {
                project.logger.warn "Repository ${repo.url} removed."
                remove repo
            }
        }
        maven {
            url "http://localhost:8081/repository/maven-public"
        }
        flatDir {
            dirs 'libs'
        }

    }
}
