#!/usr/bin/env python3

import os
from pathlib import Path
from subprocess import run
import sys

EXIT_FAILURE = 1
PROJECT_ROOT_DIR = os.path.dirname(os.path.realpath(__file__))
DOT_GRADLE_DIR = os.path.join(Path.home(), ".gradle")
GRADLE_PROPERTIES = os.path.join(DOT_GRADLE_DIR, "gradle.properties")
GRADLE_PROPERTIES_IN = os.path.join(PROJECT_ROOT_DIR, "gradle.properties.in")


def main() -> None:
    create_gradle_properties()
    run_perl_script()


def create_gradle_properties() -> None:
    intermine_checkout = os.getenv("IM_CHECKOUT")
    if intermine_checkout is None:
        print("IM_CHECKOUT must be defined", file=sys.stderr)
        sys.exit(EXIT_FAILURE)

    with open(GRADLE_PROPERTIES, "w") as f_out:
        with open(GRADLE_PROPERTIES_IN) as f_in:
            for line in f_in:
                f_out.write(
                    line.replace("@@im_checkout@@", intermine_checkout)
                )


def run_perl_script() -> None:
    perl_script = os.path.join(PROJECT_ROOT_DIR, "project_build.pl")
    perl_args = [perl_script] + sys.argv[1:]

    run(perl_args, check=True)


if __name__ == "__main__":
    main()
