CareSite.key_primaryidentifer = careSiteId
Concept.key_primaryidentifer = conceptId
ConceptClass.key_primaryidentifer = conceptClassId
ConditionEra.key_primaryidentifer = conditionEraId
ConditionOccurrence.key_primaryidentifer = conditionOccurrenceId
Cost.key_primaryidentifer = costId
DeviceExposure.key_primaryidentifer = deviceExposureId
Domain.key_primaryidentifer = domainId
DoseEra.key_primaryidentifer = doseEraId
DrugEra.key_primaryidentifer = drugEraId
DrugExposure.key_primaryidentifer = drugExposureId
Episode.key_primaryidentifer = episodeId
Location.key_primaryidentifer = locationId
Measurement.key_primaryidentifer = measurementId
Metadata.key_primaryidentifer = metadataId
Note.key_primaryidentifer = noteId
NoteNlp.key_primaryidentifer = noteNlpId
Observation.key_primaryidentifer = observationId
ObservationPeriod.key_primaryidentifer = observationPeriodId
PayerPlanPeriod.key_primaryidentifer = payerPlanPeriodId
Person.key_primaryidentifer = personId
ProcedureOccurrence.key_primaryidentifer = procedureOccurrenceId
Provider.key_primaryidentifer = providerId
Relationship.key_primaryidentifer = relationshipId
Specimen.key_primaryidentifer = specimenId
VisitDetail.key_primaryidentifer = visitDetailId
VisitOccurrence.key_primaryidentifer = visitOccurrenceId
Vocabulary.key_primaryidentifer = vocabularyId
