apply plugin: 'dbmodel'
apply plugin: 'mine-dbmodel'
apply plugin: 'integrate'
apply plugin: 'postprocess'

sourceSets {
    main {
        java {
            srcDirs = ['build/gen']
        }
        resources {
            srcDirs = ['resources']
        }
    }
}

repositories {
    ivy {
        // define in ~/.gradle/gradle.properties
        // intermine.plugin.repo=file:///your/intermine/repo/plugin/build/libs
        url project.getProperty("intermine.plugin.repo")
        layout "pattern", {
            artifact  "[artifact]-[revision].[ext]"
        }
        metadataSources {
            artifact()
        }
    }
    mavenCentral()
    maven {
        url = uri("https://plugins.gradle.org/m2/")
    }
}

dependencies {
    compile group: "org.intermine", name: "bio-core", version: System.getProperty("bioVersion"), transitive: false
    compile group: "org.intermine", name: "intermine-integrate", version: System.getProperty("imVersion")
    compile group: "org.intermine", name: "intermine-objectstore", version: System.getProperty("imVersion")
    compile group: "org.intermine", name: "intermine-model", version: System.getProperty("imVersion")
    compile group: "org.intermine", name: "intermine-resources", version: System.getProperty("imVersion") // for log4j
    compile fileTree(dir: 'libs', include: '*.jar')
    bioModel group: "org.intermine", name: "bio-model", version: System.getProperty("bioVersion"), transitive: false
    compile group: 'commons-lang', name: 'commons-lang', version: '2.6'
    compile group: 'org.apache.logging.log4j', name: 'log4j-1.2-api', version: '2.17.1'
    compile group: 'commons-collections', name: 'commons-collections', version: '3.2'
}

dbModelConfig {
    mineName = "cadremine"
    objectStoreName = "os.production"
    modelName = "genomic"
    defaultInterminePropertiesFile = "default.intermine.production.properties"
    userProfileObjectStoreName = "os.userprofile-production"
    userProfileModelName = "userprofile"
    soTermListFilePath = "dbmodel/resources/so_terms"
    soAdditionFilePath = "dbmodel/build/so_additions.xml"
}

mineDBModelConfig {
    modelName = "genomic"
    extraModelsStart = "so_additions.xml genomic_additions.xml global_additions.xml"
    extraModelsEnd = "omop_additions.xml"
}
