apply plugin: "war"
apply plugin: "webapp"
apply plugin: "com.bmuschko.cargo"

sourceSets {
    main {
        java {
            srcDirs = ["src/main/java"]
        }
        resources {
            srcDirs = ["src/main/resources"]
        }
    }
}

configurations {
    onlyRunTime
}

def explodedWebAppDir = "$buildDir/explodedWebApp"
def mergePropsDir = "$buildDir/props"

dependencies {
    compile (project(":dbmodel")) {transitive = false}
    compile group: "org.intermine", name: "bio-core", version: System.getProperty("bioVersion"), transitive: false
    compile group: "org.intermine", name: "intermine-api", version: System.getProperty("imVersion")
    compile group: "org.intermine", name: "intermine-integrate", version: System.getProperty("imVersion")
    compile group: "org.intermine", name: "intermine-model", version: System.getProperty("imVersion")
    compile group: "org.intermine", name: "intermine-objectstore", version: System.getProperty("imVersion")
    compile group: "org.intermine", name: "intermine-pathquery", version: System.getProperty("imVersion")
    compile group: "org.intermine", name: "intermine-webapp", version: System.getProperty("imVersion"), classifier: "classes"
    compile group: "org.intermine", name: "intermine-webtasks", version: System.getProperty("imVersion")

    compile group: 'commons-beanutils', name: 'commons-beanutils', version: '1.9.3'
    compile group: 'commons-io', name: 'commons-io', version: '1.2'
    compile group: 'commons-lang', name: 'commons-lang', version: '2.6'
    compile group: 'ch.qos.reload4j', name: 'reload4j', version: '1.2.22'
    compile group: 'org.slf4j', name: 'slf4j-reload4j', version: '1.7.36'
    compile group: 'cglib', name: 'cglib', version: '3.1'
    compile group: 'org.postgresql', name: 'postgresql', version: '42.2.2'
    compile group: 'com.zaxxer', name: 'HikariCP', version: '3.2.0', transitive: false
    compile group: 'org.apache.lucene', name: 'lucene-analyzers', version: '3.0.2'
    compile group: 'org.apache.lucene', name: 'lucene-highlighter', version: '3.0.2'
    compile group: 'org.apache.lucene', name: 'lucene-snowball', version: '3.0.2'
    compile group: 'org.apache.solr', name: 'solr-solrj', version: '8.11.4'
}

war {
    dependsOn 'declareExplodedWebApp', 'copyWarProperties', 'mergeProperties', 'summariseObjectStore', 'unwarBioWebApp', 'addStrutsConfig'
    finalizedBy 'warWebApp'
}

// https://github.com/intermine/intermine/issues/2162
// Temporary fix until unwarBioWebApp in the intermine plugin is fixed
task declareExplodedWebApp() {
    outputs.dir "$explodedWebAppDir/donotdeleteme"
    doLast{
        mkdir "$explodedWebAppDir/donotdeleteme"
    }
}

task copyWarProperties(type: Copy) {
    // copyMineProperties copies the intermine.properties used for building the database
    // and this might not be the same as the one needed in the WAR file where the host
    // might have a different name. So we need to overwrite it with this before building
    // the WAR file
    description "Copies mine specific intermine.properties file into resources output to be included in the WAR"
    dependsOn 'processResources'
    from (mineWarPropertyFile)
    into sourceSets.main.output.resourcesDir
    rename { fileName -> fileName.replace("$mineWarPropertyFileName", "intermine.properties") }
    inputs.sourceFiles.stopExecutionIfEmpty()
  }
}

task warWebApp(type: War) {
    dependsOn 'copyWebappContent'
    description "Create the war from the build/explodedWebAppDir directory"
    from "${explodedWebAppDir}"
    exclude "WEB-INF/web.properties"
    webInf { from "${mergePropsDir}" }
}

task copyWebappContent(type: Copy) {
    from "src/main/webapp/"
    into "${explodedWebAppDir}"
}

// java.utils.Properties so getProperty() returns null if it doesn't exist
def props = new Properties()

// read in build properties file to get the contextPath
// This has the databases as seen from the host
// mineWarPropertyFile is the one that is copied into the WAR file
// These might be the same.
file(mineBuildPropertyFile).withInputStream { props.load(it) }

webappConfig {
    mineName = "cadremine"
    objectStoreName = "os.production"
    userProfileObjectStoreName = "os.userprofile-production"
    userProfileObjectStoreWriterName = "osw.userprofile-production"
    defaultInterminePropertiesFile = "default.intermine.production.properties"
    propsDir = "$mergePropsDir"
}

// -------------------------------------------------------------------------------------------------------
// Use cargo to deploy the webapp to an existing Tomcat instance, either via the HTTP Tomcat manager or local file copy.
// -------------------------------------------------------------------------------------------------------
cargo {

    // change this to match your Tomcat major version (keep the x)
    containerId = 'tomcat9x'

    int port = 8080
    if (props.getProperty("webapp.port") != null) {
        port = props.getProperty("webapp.port").toInteger()
    }

    deployable {
        context = props.getProperty("webapp.path")
        println "Using context: $context"
    }

    local {
        if (props.getProperty("webapp.homedir") != null) {
            homeDir = file(props.getProperty("webapp.homedir"))
            println "Using homeDir: $homeDir"
        }

        // https://stackoverflow.com/questions/138511/what-are-java-command-line-options-to-set-to-allow-jvm-to-be-remotely-debugged

        // Options on -Xrunjdwp or agentlib:jdwp arguments are :

        // transport=dt_socket : means the way used to connect to JVM (socket is a good choice, it can be used to debug a distant computer)
        // address=5005 : TCP/IP port exposed, to connect from the debugger (will only allow local connections)
        // suspend=y : if 'y', tell the JVM to wait until debugger is attached to begin execution, otherwise (if 'n'), starts execution right away.

        // String not array syntax for Gradle 4.9
        jvmArgs = """
            -Djava.awt.headless=true
            -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
        """.trim()
    }

    // change these to match your Tomcat host and tomcat-users config
    remote {
        // if "hostname" is defined in properties file, use that
        if (props.getProperty("webapp.hostname") != null) {
            hostname = props.getProperty("webapp.hostname")
        } else if (props.getProperty("webapp.deploy.url") != null) {
            hostname = getServerName(props.getProperty("webapp.deploy.url"))
        } else {
            hostname = "localhost"
        }

        // if "protocol" is defined in properties file, use that
        if (props.getProperty("webapp.protocol") != null) {
            protocol = props.getProperty("webapp.protocol")
        } else {
            protocol = "http"
        }

        username = props.getProperty("webapp.manager")
        password = props.getProperty("webapp.password")
    }
}

cargoStartLocal.dependsOn war
cargoRunLocal.dependsOn war
cargoRedeployLocal.dependsOn war
cargoDeployRemote.dependsOn war
cargoRedeployRemote.dependsOn war

// gets the hostname from the old intermine parameter, e.g. http://localhost:8080 > localhost
String getServerName(String deployUrl) {
    // chop off protocol
    if (deployUrl != null && deployUrl.indexOf("/") >= 0) {
        // https:// or http://
        deployUrl = deployUrl.substring(deployUrl.indexOf("/") + 2, deployUrl.length())
    }

    // chop off port
    if (deployUrl != null && deployUrl.contains(":")) {
        // localhost:8080
        String[] bits = deployUrl.split(":")
        deployUrl = bits[0]
    }

    return deployUrl
}
