---
# yamllint disable rule:line-length
name: deploy
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - .github/workflows/deploy.yml
            - bin/install_boot.py
            - bin/install.py
            - bin/release.py
            - build.gradle
            - data/**
            - dbmodel/**
            - docker-compose.yml
            - .env
            - extra/**
            - gradle.properties.in
            - make-loader.sh
            - postgres/**
            - project_build
            - project.xml
            - settings.gradle
            - solr/**
            - tomcat/**
            - webapp/**

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Install prerequisites
              run: |
                  set -euo pipefail
                  sudo apt-get -y install dar
            - name: Set up JDK 8
              uses: actions/setup-java@v1
              with:
                  java-version: '8'

            - name: Checkout cadremine
              uses: actions/checkout@v4
              with:
                  path: "cadremine"

            - name: Checkout intermine
              uses: actions/checkout@v4
              with:
                  repository: "intermine/intermine"
                  ref: "eclipse-setup"
                  path: "intermine"

            - name: Release
              run: |
                  set -euxo pipefail
                  ${{ env.PYTHON }} ${GITHUB_WORKSPACE}/cadremine/bin/release.py ${GITHUB_WORKSPACE}/intermine docker

            - name: Install
              run: |
                  set -euxo pipefail
                  export PGPASSWORD=postgres
                  # Note: System python3
                  python3 ${GITHUB_WORKSPACE}/cadremine/release/install_boot.py ${GITHUB_WORKSPACE}/intermine -v

            - name: Dump Docker logs
              if: failure()
              run: |
                  set -euo pipefail
                  cd ${GITHUB_WORKSPACE}
                  sleep 120
                  compose_file=${GITHUB_WORKSPACE}/cadremine/release/docker-compose.yml
                  docker compose -f ${compose_file} logs bluegenes
                  docker compose -f ${compose_file} logs nexus
                  docker compose -f ${compose_file} logs postgres
                  docker compose -f ${compose_file} logs solr
                  docker compose -f ${compose_file} logs tomcat
