---
# yamllint disable rule:line-length
name: deploy
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - .github/workflows/deploy.yml
            - bin/install_boot.py
            - bin/install.py
            - bin/release.py
            - build.gradle
            - data/**
            - dbmodel/**
            - docker-compose.yml
            - .env
            - extra/**
            - gradle.properties.in
            - gradle-wrapper.properties.in
            - make-loader.sh
            - postgres/**
            - project_build
            - project.xml
            - settings.gradle
            - solr/**
            - tomcat/**
            - webapp/**

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Install prerequisites
              run: |
                  set -euo pipefail
                  sudo apt-get -y install dar wait-for-it
            - name: Set up JDK 8
              uses: actions/setup-java@v1
              with:
                  java-version: '8'

            - name: Checkout cadremine
              uses: actions/checkout@v4
              with:
                  path: "cadremine"

            - name: Checkout intermine
              uses: actions/checkout@v4
              with:
                  repository: "intermine/intermine"
                  ref: "eclipse-setup"
                  path: "intermine"

            - name: Release
              run: |
                  set -euxo pipefail
                  python3 ${GITHUB_WORKSPACE}/cadremine/bin/release.py ${GITHUB_WORKSPACE}/intermine docker

            - name: Start Docker
              run: |
                  set -euxo pipefail
                  cd ${GITHUB_WORKSPACE}
                  compose_file=${GITHUB_WORKSPACE}/cadremine/docker-compose.yml
                  docker compose -f ${compose_file} up
                  # Wait for Nexus
                  wait-for-it localhost:8081

            - name: Populate Sonatype Nexus repository
              run: |
                  set -euxo pipefail
                  python3 -m virtualenv ${HOME}/venv
                  PYTHON=${HOME}/venv/bin/python
                  ${PYTHON} -m pip install ${GITHUB_WORKSPACE}/requirements.txt
                  ${PYTHON} ${GITHUB_WORKSPACE}/cadremine/bin/initialise_nexus.py -v
                  python3 ${GITHUB_WORKSPACE}/cadremine/bin/download_maven_artifacts.py ${GITHUB_WORKSPACE}/intermine http://localhost:8081/repository/maven-public -v

            - name: Install
              run: |
                  set -euxo pipefail
                  export PGPASSWORD=postgres
                  python3 ${GITHUB_WORKSPACE}/cadremine/bin/install_boot.py ${GITHUB_WORKSPACE}/intermine ${GITHUB_WORKSPACE}/cadremine/release -v --recreate_databases --offline

            - name: Dump Docker logs
              if: failure()
              run: |
                  set -euo pipefail
                  cd ${GITHUB_WORKSPACE}
                  sleep 120
                  compose_file=${GITHUB_WORKSPACE}/cadremine/docker-compose.yml
                  docker compose -f ${compose_file} logs bluegenes
                  docker compose -f ${compose_file} logs nexus
                  docker compose -f ${compose_file} logs postgres
                  docker compose -f ${compose_file} logs solr
                  docker compose -f ${compose_file} logs tomcat
