---
# yamllint disable rule:line-length
name: deploy
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - .github/workflows/deploy.yml
            - bin/install_boot.py
            - bin/install.py
            - bin/release.py
            - build.gradle
            - data/**
            - dbmodel/**
            - docker-compose.yml
            - .env
            - extra/**
            - gradle.properties.in
            - make-loader.sh
            - postgres/**
            - project_build
            - project.xml
            - settings.gradle
            - solr/**
            - tomcat/**
            - webapp/**

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            VENV: /home/runner/venv
            PYTHON: /home/runner/venv/bin/python
        steps:
            - name: Install prerequisites
              run: |
                  set -euo pipefail
                  sudo apt-get -y install dar
            - name: Set up JDK 8
              uses: actions/setup-java@v1
              with:
                  java-version: '8'

            - name: Checkout cadremine
              uses: actions/checkout@v4
              with:
                  path: "cadremine"

            - name: Checkout intermine
              uses: actions/checkout@v4
              with:
                  repository: "intermine/intermine"
                  ref: "eclipse-setup"
                  path: "intermine"

            - name: Python setup
              run: |
                  set -euxo pipefail
                  python3 -m venv ${{ env.VENV }}
                  ${{ env.PYTHON }} -m pip install -r ${GITHUB_WORKSPACE}/cadremine/requirements.txt

            - name: Install intermine
              run: |
                  set -euxo pipefail
                  export PSQL_USER=test
                  export PSQL_PWD=test
                  export PSQL_HOST=localhost
                  ${{ env.PYTHON }}  ${GITHUB_WORKSPACE}/intermine/config/lib/install_intermine.py

            - name: Copy cadremine.properties
              run: |
                  set -euxo pipefail
                  intermine_dir=${HOME}/.intermine
                  mkdir -p "${intermine_dir}"
                  cp ${GITHUB_WORKSPACE}/cadremine/data/cadremine.properties "${intermine_dir}"

            - name: Release
              run: |
                  set -euxo pipefail
                  ${{ env.PYTHON }} ${GITHUB_WORKSPACE}/cadremine/bin/release.py ${GITHUB_WORKSPACE}/intermine

            - name: Install
              run: |
                  set -euxo pipefail
                  # Note: System python3
                  python3 ${GITHUB_WORKSPACE}/cadremine/release/install_boot.py

            - name: Dump Docker logs
              if: failure()
              run: |
                  set -euo pipefail
                  cd ${GITHUB_WORKSPACE}
                  sleep 120
                  compose_file=${GITHUB_WORKSPACE}/cadremine/release/docker-compose.yml
                  docker compose -f ${compose_file} logs bluegenes
                  docker compose -f ${compose_file} logs nexus
                  docker compose -f ${compose_file} logs postgres
                  docker compose -f ${compose_file} logs solr
                  docker compose -f ${compose_file} logs tomcat
