---
# yamllint disable rule:line-length
name: dev
# yamllint disable-line rule:truthy
on: push

jobs:
    dev:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:11
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432
        steps:
            - uses: actions/checkout@v4
              with:
                  path: "cadremine"
            - uses: actions/checkout@v4
              with:
                  repository: "intermine/intermine"
                  ref: "eclipse-setup"
                  path: "intermine"
            - name: Set up development environment
              run: |
                  set -euxo pipefail
                  ls -l ${GITHUB_WORKSPACE}/..
                  cd ${GITHUB_WORKSPACE}
                  ls -l
                  export IM_CHECKOUT=${GITHUB_WORKSPACE}/../intermine
                  python3 bin/init.py
