---
# yamllint disable rule:line-length
name: dev
# yamllint disable-line rule:truthy
on: push

jobs:
    dev:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:11
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432
        steps:
            - uses: actions/checkout@v4
              run: |
                  set -euo pipefail
                  cd ${GITHUB_WORKSPACE}
                  python3 bin/init.py
