---
# yamllint disable rule:line-length
name: dev
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - .github/workflows/dev.yml
            - bin/build.py
            - build.gradle
            - data/**
            - dbmodel/**
            - extra/**
            - gradle.properties.in
            - make-loader.sh
            - project_build
            - project.xml
            - settings.gradle
            - webapp/**

jobs:
    dev:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:11
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432
        steps:
            - name: Install prerequisites
              run: |
                  set -euo pipefail
                  sudo apt-get install libxml-perl libtext-glob-perl
            - name: Set up JDK 8
              uses: actions/setup-java@v5
              with:
                distribution: 'zulu'
                java-version: '8'
            - uses: actions/checkout@v6
              with:
                  path: "cadremine"
            - uses: actions/checkout@v6
              with:
                  repository: "intermine/intermine"
                  ref: "eclipse-setup"
                  path: "intermine"
            - name: Install intermine
              run: |
                  set -euxo pipefail
                  export PSQL_USER=test
                  export PSQL_PWD=test
                  export PSQL_HOST=localhost
                  python3 ${GITHUB_WORKSPACE}/intermine/config/lib/install_intermine.py

            - name: Set up development environment
              run: |
                  set -euxo pipefail
                  cd ${GITHUB_WORKSPACE}/cadremine
                  python3 bin/build.py ${GITHUB_WORKSPACE}/intermine --with_sudo --verbose
